# Generated by Django 5.0.7 on 2024-07-30 06:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_booking_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
