# Generated by Django 5.0.7 on 2024-07-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0004_userrole_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='auth.permission'),
        ),
    ]
